import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../../core/widgets/app_scaffold.dart';
import '../../../repositories/store_repository.dart';
import '../../../services/advanced_report_service.dart';
import '../../../services/ollama_service.dart';

String _money(dynamic v) => '₹${((v as num?)?.toDouble() ?? 0).toStringAsFixed(2)}';

class _AnalysisData {
  final List<Map<String, dynamic>> customerLastVisit;
  final List<Map<String, dynamic>> slowMoving;
  final List<Map<String, dynamic>> topProducts;
  final Map<String, dynamic> festival;
  final String? narrative;
  final bool ollamaEnabled;
  final String ollamaBaseUrl;

  _AnalysisData({
    required this.customerLastVisit,
    required this.slowMoving,
    required this.topProducts,
    required this.festival,
    required this.narrative,
    required this.ollamaEnabled,
    required this.ollamaBaseUrl,
  });
}

/// A single dashboard combining four data-backed reports (customers overdue
/// for a visit, slow-moving stock, top sellers, upcoming-festival restock
/// suggestions) with an optional plain-English summary generated by a local
/// Ollama model. Every section works from plain SQL and stays fully useful
/// with Ollama off/unreachable — the narrative is an enhancement, not a
/// dependency. See AdvancedReportService for the underlying queries and
/// OllamaService for why a failed AI call never surfaces as an error here.
class AIAnalysisScreen extends StatefulWidget {
  const AIAnalysisScreen({super.key});

  @override
  State<AIAnalysisScreen> createState() => _AIAnalysisScreenState();
}

class _AIAnalysisScreenState extends State<AIAnalysisScreen> {
  final _reportService = AdvancedReportService();
  late Future<_AnalysisData> _future;

  @override
  void initState() {
    super.initState();
    _future = _load();
  }

  Future<_AnalysisData> _load() async {
    final customerLastVisitAll = await _reportService.getCustomerLastVisit();
    final slowMoving = await _reportService.getSlowMovingStock(limit: 10);
    final topProducts = await _reportService.getTopSellingProducts(limit: 5);
    final festival = await _reportService.getFestivalStockSuggestions();
    final ollamaConfig = await StoreRepository().getOllamaConfig();

    final customerLastVisit = customerLastVisitAll.take(10).toList();

    String? narrative;
    if (ollamaConfig.enabled) {
      final prompt = _buildPrompt(
        customerLastVisit: customerLastVisit,
        slowMoving: slowMoving,
        topProducts: topProducts,
        festival: festival,
      );
      narrative = await OllamaService().generate(
        prompt: prompt,
        baseUrl: ollamaConfig.baseUrl,
        model: ollamaConfig.model,
      );
    }

    return _AnalysisData(
      customerLastVisit: customerLastVisit,
      slowMoving: slowMoving,
      topProducts: topProducts,
      festival: festival,
      narrative: narrative,
      ollamaEnabled: ollamaConfig.enabled,
      ollamaBaseUrl: ollamaConfig.baseUrl,
    );
  }

  String _buildPrompt({
    required List<Map<String, dynamic>> customerLastVisit,
    required List<Map<String, dynamic>> slowMoving,
    required List<Map<String, dynamic>> topProducts,
    required Map<String, dynamic> festival,
  }) {
    final buffer = StringBuffer()
      ..writeln(
        'You are a business assistant for a small Indian supermarket. '
        'Using ONLY the data below, write a short plain-English summary '
        '(under 120 words) with 2-3 concrete action suggestions. Do not '
        'invent numbers that are not given below.',
      )
      ..writeln();

    final overdue = customerLastVisit.where((c) => c['daysSinceVisit'] == null || (c['daysSinceVisit'] as int) > 30);
    buffer.writeln('Customers overdue for a return visit: ${overdue.length}');

    buffer.writeln('Top selling products: ${topProducts.map((p) => p['name']).join(', ')}');

    buffer.writeln('Slow-moving stock (in stock, barely selling): ${slowMoving.length} items'
        '${slowMoving.isNotEmpty ? ' — e.g. ${slowMoving.take(5).map((p) => p['name']).join(', ')}' : ''}');

    if (festival['hasFestival'] == true) {
      buffer.writeln(
        'Upcoming festival: ${festival['festivalName']} in ${festival['daysUntil']} days.',
      );
      if (festival['hasHistoricalData'] == true) {
        final suggestions = festival['suggestions'] as List<dynamic>;
        buffer.writeln('Products that sold well around this festival last year: '
            '${suggestions.take(5).map((p) => p['name']).join(', ')}');
      } else {
        buffer.writeln('No sales history available yet for that festival window.');
      }
    } else {
      buffer.writeln('No festival configured in the calendar.');
    }

    return buffer.toString();
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'AI Analysis',
      body: FutureBuilder<_AnalysisData>(
        future: _future,
        builder: (context, snapshot) {
          if (snapshot.connectionState != ConnectionState.done) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: Text('Could not load analysis: ${snapshot.error}'));
          }
          final data = snapshot.data!;
          return RefreshIndicator(
            onRefresh: () async {
              final next = _load();
              setState(() => _future = next);
              await next;
            },
            child: ListView(
              padding: const EdgeInsets.all(12),
              children: [
                _NarrativeCard(data: data),
                const SizedBox(height: 12),
                _FestivalSection(festival: data.festival),
                const SizedBox(height: 12),
                _CustomerVisitSection(customers: data.customerLastVisit),
                const SizedBox(height: 12),
                _SlowMovingSection(items: data.slowMoving),
                const SizedBox(height: 12),
                _TopProductsSection(products: data.topProducts),
              ],
            ),
          );
        },
      ),
    );
  }
}

class _NarrativeCard extends StatelessWidget {
  final _AnalysisData data;

  const _NarrativeCard({required this.data});

  @override
  Widget build(BuildContext context) {
    if (!data.ollamaEnabled) {
      return Card(
        color: Theme.of(context).colorScheme.surfaceContainerHighest.withValues(alpha: 0.4),
        child: ListTile(
          leading: const Icon(Icons.smart_toy_outlined),
          title: const Text('AI summary is off'),
          subtitle: const Text('Enable Ollama in Settings to get a plain-English summary above these reports.'),
          trailing: TextButton(
            onPressed: () => context.push('/settings'),
            child: const Text('Settings'),
          ),
        ),
      );
    }
    if (data.narrative == null) {
      return Card(
        color: Colors.orange.withValues(alpha: 0.1),
        child: ListTile(
          leading: const Icon(Icons.warning_amber_rounded, color: Colors.orange),
          title: const Text('Could not reach Ollama'),
          subtitle: Text('No response from ${data.ollamaBaseUrl}. Showing data-only reports below.'),
        ),
      );
    }
    return Card(
      color: Theme.of(context).colorScheme.primaryContainer.withValues(alpha: 0.3),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Icon(Icons.smart_toy_outlined),
            const SizedBox(width: 12),
            Expanded(child: Text(data.narrative!)),
          ],
        ),
      ),
    );
  }
}

class _SectionCard extends StatelessWidget {
  final String title;
  final IconData icon;
  final Widget child;

  const _SectionCard({required this.title, required this.icon, required this.child});

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 18, color: Theme.of(context).primaryColor),
                const SizedBox(width: 8),
                Text(title, style: const TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),
            const SizedBox(height: 8),
            child,
          ],
        ),
      ),
    );
  }
}

class _FestivalSection extends StatelessWidget {
  final Map<String, dynamic> festival;

  const _FestivalSection({required this.festival});

  @override
  Widget build(BuildContext context) {
    if (festival['hasFestival'] != true) {
      return const _SectionCard(
        title: 'Festival Stock Suggestions',
        icon: Icons.celebration_outlined,
        child: Text('No festivals configured. Add one from Settings → Utilities → Festival Calendar.'),
      );
    }

    final name = festival['festivalName'] as String;
    final daysUntil = festival['daysUntil'] as int;
    final notes = festival['festivalNotes'] as String?;
    final hasData = festival['hasHistoricalData'] == true;
    final suggestions = (festival['suggestions'] as List<dynamic>).cast<Map<String, dynamic>>();

    return _SectionCard(
      title: 'Festival Stock Suggestions',
      icon: Icons.celebration_outlined,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('$name — in $daysUntil day${daysUntil == 1 ? '' : 's'}',
              style: const TextStyle(fontWeight: FontWeight.w600)),
          if (notes != null) ...[
            const SizedBox(height: 4),
            Text(notes, style: const TextStyle(fontSize: 12, color: Colors.grey)),
          ],
          const SizedBox(height: 8),
          if (!hasData)
            const Text('No sales history from last year in this festival\'s window yet.')
          else
            ...suggestions.map((s) => ListTile(
                  dense: true,
                  contentPadding: EdgeInsets.zero,
                  leading: Icon(
                    s['needsRestock'] == true ? Icons.priority_high : Icons.check_circle_outline,
                    color: s['needsRestock'] == true ? Colors.red : Colors.green,
                    size: 20,
                  ),
                  title: Text(s['name'] as String),
                  subtitle: Text(
                    'Sold ${s['quantitySoldLastYear']} last year around this festival · '
                    'In stock now: ${s['currentStock']}',
                  ),
                  trailing: Text(_money(s['revenueLastYear'])),
                )),
        ],
      ),
    );
  }
}

class _CustomerVisitSection extends StatelessWidget {
  final List<Map<String, dynamic>> customers;

  const _CustomerVisitSection({required this.customers});

  @override
  Widget build(BuildContext context) {
    return _SectionCard(
      title: 'Customers Overdue for a Visit',
      icon: Icons.people_outline,
      child: customers.isEmpty
          ? const Text('No customers yet.')
          : Column(
              children: customers.map((c) {
                final days = c['daysSinceVisit'] as int?;
                return ListTile(
                  dense: true,
                  contentPadding: EdgeInsets.zero,
                  title: Text(c['name'] as String),
                  subtitle: Text(c['phone'] as String),
                  trailing: Text(
                    days == null ? 'Never purchased' : '$days day${days == 1 ? '' : 's'} ago',
                    style: TextStyle(
                      color: days == null || days > 60 ? Colors.red : Colors.grey.shade700,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                );
              }).toList(),
            ),
    );
  }
}

class _SlowMovingSection extends StatelessWidget {
  final List<Map<String, dynamic>> items;

  const _SlowMovingSection({required this.items});

  @override
  Widget build(BuildContext context) {
    return _SectionCard(
      title: 'Slow Moving Stock (last 60 days)',
      icon: Icons.hourglass_bottom,
      child: items.isEmpty
          ? const Text('Nothing looks slow-moving right now.')
          : Column(
              children: items.map((p) {
                final days = p['daysSinceLastSale'] as int?;
                return ListTile(
                  dense: true,
                  contentPadding: EdgeInsets.zero,
                  title: Text(p['name'] as String),
                  subtitle: Text('In stock: ${p['stockQuantity']} · Sold in window: ${p['soldQuantity']}'),
                  trailing: Text(
                    days == null ? 'Never sold' : 'Last sold $days d ago',
                    style: const TextStyle(fontSize: 12, color: Colors.grey),
                  ),
                );
              }).toList(),
            ),
    );
  }
}

class _TopProductsSection extends StatelessWidget {
  final List<Map<String, dynamic>> products;

  const _TopProductsSection({required this.products});

  @override
  Widget build(BuildContext context) {
    return _SectionCard(
      title: 'Top Selling Products',
      icon: Icons.trending_up,
      child: products.isEmpty
          ? const Text('No sales yet.')
          : Column(
              children: products.map((p) {
                return ListTile(
                  dense: true,
                  contentPadding: EdgeInsets.zero,
                  title: Text(p['name'] as String),
                  subtitle: Text('Qty sold: ${p['quantity']}'),
                  trailing: Text(_money(p['revenue']), style: const TextStyle(fontWeight: FontWeight.bold)),
                );
              }).toList(),
            ),
    );
  }
}
