import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/widgets/app_scaffold.dart';
import '../../../models/product_model.dart';
import '../../../repositories/product_repository.dart';
import '../../../repositories/product_batch_repository.dart';
import '../../../repositories/store_repository.dart';
import '../../../services/barcode_label_service.dart';

/// One entry in the "Item List" queue below the input panels — a product,
/// how many label copies to print for it, and the packing/expiry dates
/// that'll print on the label (auto-suggested from the product's nearest
/// batch, editable in case a specific batch needs different ones).
class _BarcodeQueueItem {
  final Product product;
  final int copies;
  final DateTime? packingDate;
  final DateTime? expiryDate;

  const _BarcodeQueueItem({
    required this.product,
    required this.copies,
    this.packingDate,
    this.expiryDate,
  });
}

/// Paints a rough, cosmetic bar pattern derived from the item code, purely
/// so the Preview panel looks like a barcode label. This is NOT the barcode
/// that gets printed — the real Code128 barcode is generated by
/// [BarcodeLabelService] from the product's actual barcode value.
class _BarcodeBarsPainter extends CustomPainter {
  final String data;

  _BarcodeBarsPainter(this.data);

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()..color = Colors.black;
    final seed = data.isEmpty ? '0123456789' : data;
    const barCount = 34;
    final barSlot = size.width / barCount;
    for (var i = 0; i < barCount; i++) {
      final code = seed.codeUnitAt(i % seed.length);
      final drawBar = (code + i) % 3 != 0;
      if (drawBar) {
        canvas.drawRect(
          Rect.fromLTWH(i * barSlot, 0, barSlot * 0.6, size.height),
          paint,
        );
      }
    }
  }

  @override
  bool shouldRepaint(covariant _BarcodeBarsPainter oldDelegate) => oldDelegate.data != data;
}

class BarcodeGeneratorScreen extends ConsumerStatefulWidget {
  const BarcodeGeneratorScreen({super.key});

  @override
  ConsumerState<BarcodeGeneratorScreen> createState() => _BarcodeGeneratorScreenState();
}

class _BarcodeGeneratorScreenState extends ConsumerState<BarcodeGeneratorScreen> {
  final _itemNameController = TextEditingController();
  final _itemCodeController = TextEditingController();
  final _noOfLabelsController = TextEditingController(text: '1');

  final _itemNameFocusNode = FocusNode();

  List<Product> _nameSuggestions = [];
  bool _showSuggestions = false;
  Product? _selectedProduct;

  // Auto-suggested from the resolved product's nearest-expiry batch (see
  // _suggestBatchDatesFor), but editable — a label being printed for a
  // specific incoming batch may not match whatever batch happens to sort
  // first.
  DateTime? _packingDate;
  DateTime? _expiryDate;

  bool _isBusy = false; // name/code lookups
  bool _isPrinting = false;

  final List<_BarcodeQueueItem> _queueItems = [];

  // Bumped on every new search so a slow, stale response can't clobber a
  // newer one's results.
  int _searchRequestId = 0;

  // Fetched once and cached — every label on this screen prints under the
  // same shop, so there's no reason to re-query per item/print.
  String _shopName = '';

  @override
  void initState() {
    super.initState();
    _itemNameFocusNode.addListener(() {
      if (!_itemNameFocusNode.hasFocus) {
        setState(() => _showSuggestions = false);
      }
    });
    StoreRepository().getStore().then((store) {
      if (mounted) setState(() => _shopName = store.name);
    });
  }

  @override
  void dispose() {
    _itemNameController.dispose();
    _itemCodeController.dispose();
    _noOfLabelsController.dispose();
    _itemNameFocusNode.dispose();
    super.dispose();
  }

  /// Called once a scan/search/typed code resolves to a real [Product] —
  /// pre-fills Packing Date and Expiry Date from that product's
  /// soonest-expiry batch, if it has one (same batch informs both — they're
  /// two dates off the same incoming stock). Either field stays editable
  /// afterward, so this is just a starting point, not a lock.
  Future<void> _suggestBatchDatesFor(Product product) async {
    try {
      final batches = await ProductBatchRepository().getByProduct(product.id);
      if (batches.isEmpty || !mounted) return;
      final batch = batches.first;
      setState(() {
        if (batch.packingDate != null) {
          _packingDate = DateTime.fromMillisecondsSinceEpoch(batch.packingDate! * 1000);
        }
        if (batch.expiryDate != null) {
          _expiryDate = DateTime.fromMillisecondsSinceEpoch(batch.expiryDate! * 1000);
        }
      });
    } catch (_) {
      // No batch history yet, or a lookup hiccup — dates just stay
      // whatever the user already has (usually blank), not a hard failure.
    }
  }

  Future<void> _pickPackingDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _packingDate ?? DateTime.now(),
      firstDate: DateTime(2020),
      lastDate: DateTime(2100),
    );
    if (picked != null && mounted) setState(() => _packingDate = picked);
  }

  Future<void> _pickExpiryDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _expiryDate ?? DateTime.now(),
      firstDate: DateTime(2020),
      lastDate: DateTime(2100),
    );
    if (picked != null && mounted) setState(() => _expiryDate = picked);
  }

  String _formatDate(DateTime d) =>
      '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';

  Future<void> _onNameChanged(String query) async {
    _selectedProduct = null;
    if (query.trim().isEmpty) {
      setState(() {
        _nameSuggestions = [];
        _showSuggestions = false;
      });
      return;
    }
    final requestId = ++_searchRequestId;
    try {
      final results = await ref.read(productRepositoryProvider).search(query.trim());
      if (!mounted || requestId != _searchRequestId) return;
      setState(() {
        _nameSuggestions = results;
        _showSuggestions = results.isNotEmpty;
      });
    } catch (_) {
      // Ignore transient lookup failures — the user can still type/scan
      // the code directly.
    }
  }

  void _pickSuggestion(Product product) {
    setState(() {
      _selectedProduct = product;
      _itemNameController.text = product.displayName?.isNotEmpty == true ? product.displayName! : product.name;
      _itemCodeController.text = product.barcode;
      _nameSuggestions = [];
      _showSuggestions = false;
      _packingDate = null;
      _expiryDate = null;
    });
    _itemNameFocusNode.unfocus();
    _suggestBatchDatesFor(product);
  }

  Future<void> _lookupByCode(String code) async {
    final trimmed = code.trim();
    if (trimmed.isEmpty) return;
    setState(() => _isBusy = true);
    try {
      final matches = await ref.read(productRepositoryProvider).getByBarcode(trimmed);
      if (!mounted) return;
      if (matches.isNotEmpty) {
        final product = matches.first;
        setState(() {
          _selectedProduct = product;
          _itemNameController.text = product.displayName?.isNotEmpty == true ? product.displayName! : product.name;
          _itemCodeController.text = product.barcode;
          _packingDate = null;
          _expiryDate = null;
        });
        _suggestBatchDatesFor(product);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('No item found for code "$trimmed"'), backgroundColor: Colors.red),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Lookup failed: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  Future<void> _addForBarcode() async {
    if (_itemNameController.text.trim().isEmpty || _itemCodeController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Item Name and Item Code are required'), backgroundColor: Colors.red),
      );
      return;
    }
    final copies = int.tryParse(_noOfLabelsController.text.trim());
    if (copies == null || copies <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No of Labels must be a positive number'), backgroundColor: Colors.red),
      );
      return;
    }

    setState(() => _isBusy = true);
    try {
      var product = _selectedProduct;
      // If the user typed/scanned the code directly rather than picking a
      // name suggestion, resolve it against the real product record now —
      // the printed PDF needs the actual Product, not just typed text.
      if (product == null || product.barcode != _itemCodeController.text.trim()) {
        final matches = await ref.read(productRepositoryProvider).getByBarcode(_itemCodeController.text.trim());
        if (matches.isEmpty) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Item Code does not match any known item'),
                backgroundColor: Colors.red,
              ),
            );
          }
          return;
        }
        product = matches.first;
      }

      setState(() {
        _queueItems.add(
          _BarcodeQueueItem(
            product: product!,
            copies: copies,
            packingDate: _packingDate,
            expiryDate: _expiryDate,
          ),
        );
        _itemNameController.clear();
        _itemCodeController.clear();
        _noOfLabelsController.text = '1';
        _selectedProduct = null;
        _nameSuggestions = [];
        _showSuggestions = false;
        _packingDate = null;
        _expiryDate = null;
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Added to barcode list'), backgroundColor: Colors.green),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  void _removeQueueItem(int index) {
    setState(() => _queueItems.removeAt(index));
  }

  Future<void> _print() async {
    if (_queueItems.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Add at least one item before printing'), backgroundColor: Colors.red),
      );
      return;
    }

    setState(() => _isPrinting = true);
    try {
      final expanded = <BarcodeLabelData>[];
      for (final item in _queueItems) {
        expanded.addAll(
          List.filled(
            item.copies,
            BarcodeLabelData(
              product: item.product,
              shopName: _shopName,
              packingDate: item.packingDate,
              expiryDate: item.expiryDate,
            ),
          ),
        );
      }
      final pdfBytes = await BarcodeLabelService.generateLabelSheet(expanded);
      if (!mounted) return;
      await BarcodeLabelService.printLabels(context, pdfBytes);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Labels sent to printer'), backgroundColor: Colors.green),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Print failed: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isPrinting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'Barcode Generator',
      actions: [
        IconButton(
          icon: _isPrinting
              ? const SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                )
              : const Icon(Icons.print),
          tooltip: 'Print',
          onPressed: _isPrinting ? null : _print,
        ),
      ],
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            LayoutBuilder(
              builder: (context, constraints) {
                final isNarrow = constraints.maxWidth < 800;
                final formPanel = _buildFormPanel();
                final previewPanel = _buildPreviewPanel();
                if (isNarrow) {
                  return Column(
                    children: [
                      formPanel,
                      const SizedBox(height: 16),
                      previewPanel,
                    ],
                  );
                }
                return Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(flex: 3, child: formPanel),
                    const SizedBox(width: 16),
                    Expanded(flex: 2, child: previewPanel),
                  ],
                );
              },
            ),
            const SizedBox(height: 24),
            _buildItemListPanel(),
          ],
        ),
      ),
    );
  }

  Widget _buildFormPanel() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Enter item details to add for barcode',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 16),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(flex: 3, child: _buildNameField()),
                const SizedBox(width: 12),
                Expanded(
                  flex: 2,
                  child: TextField(
                    controller: _itemCodeController,
                    decoration: const InputDecoration(
                      labelText: 'Item Code *',
                      helperText: 'Type, scan, or auto-filled from Item Name',
                    ),
                    onSubmitted: _lookupByCode,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  flex: 1,
                  child: TextField(
                    controller: _noOfLabelsController,
                    decoration: const InputDecoration(labelText: 'No of Labels *'),
                    keyboardType: TextInputType.number,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Expanded(
                  flex: 2,
                  child: InkWell(
                    onTap: _pickPackingDate,
                    child: InputDecorator(
                      decoration: const InputDecoration(
                        labelText: 'Packing Date (optional)',
                        helperText: 'Auto-suggested from the item\'s nearest batch — tap to change',
                        suffixIcon: Icon(Icons.calendar_today, size: 18),
                      ),
                      child: Text(_packingDate == null ? 'Not set' : _formatDate(_packingDate!)),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  flex: 2,
                  child: InkWell(
                    onTap: _pickExpiryDate,
                    child: InputDecorator(
                      decoration: const InputDecoration(
                        labelText: 'Expiry Date (optional)',
                        helperText: 'Auto-suggested from the item\'s nearest batch — tap to change',
                        suffixIcon: Icon(Icons.calendar_today, size: 18),
                      ),
                      child: Text(_expiryDate == null ? 'Not set' : _formatDate(_expiryDate!)),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  flex: 3,
                  child: SizedBox(
                    height: 48,
                    child: ElevatedButton.icon(
                      onPressed: _isBusy ? null : _addForBarcode,
                      icon: _isBusy
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Icon(Icons.add),
                      label: const Text('Add for Barcode'),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildNameField() {
    return Stack(
      children: [
        TextField(
          controller: _itemNameController,
          focusNode: _itemNameFocusNode,
          decoration: const InputDecoration(labelText: 'Item Name *'),
          onChanged: _onNameChanged,
        ),
        if (_showSuggestions)
          Positioned(
            top: 58,
            left: 0,
            right: 0,
            child: Material(
              elevation: 4,
              child: ConstrainedBox(
                constraints: const BoxConstraints(maxHeight: 220),
                child: ListView.builder(
                  shrinkWrap: true,
                  padding: EdgeInsets.zero,
                  itemCount: _nameSuggestions.length,
                  itemBuilder: (context, index) {
                    final product = _nameSuggestions[index];
                    return ListTile(
                      dense: true,
                      title: Text(product.name),
                      subtitle: Text(product.barcode),
                      onTap: () => _pickSuggestion(product),
                    );
                  },
                ),
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildPreviewPanel() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Preview', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const SizedBox(height: 16),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey.shade400),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Column(
                children: [
                  Text(
                    _shopName.isEmpty ? '(Shop Name)' : _shopName,
                    style: const TextStyle(fontSize: 11, fontWeight: FontWeight.bold),
                    textAlign: TextAlign.center,
                  ),
                  Text(
                    _itemNameController.text.trim().isEmpty ? '(Product Name)' : _itemNameController.text.trim(),
                    style: const TextStyle(fontSize: 12),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: CustomPaint(
                      painter: _BarcodeBarsPainter(_itemCodeController.text.trim()),
                      size: Size.infinite,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    _itemCodeController.text.trim().isEmpty ? '(Barcode Number)' : _itemCodeController.text.trim(),
                    style: const TextStyle(fontSize: 11),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'MRP Rs.${(_selectedProduct?.mrp ?? 0).toStringAsFixed(2)}   '
                    'SP Rs.${(_selectedProduct?.retailPrice ?? 0).toStringAsFixed(2)}',
                    style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold),
                    textAlign: TextAlign.center,
                  ),
                  if (_packingDate != null || _expiryDate != null)
                    Text(
                      [
                        if (_packingDate != null) 'Pkd: ${_formatDate(_packingDate!)}',
                        if (_expiryDate != null) 'Exp: ${_formatDate(_expiryDate!)}',
                      ].join('   '),
                      style: const TextStyle(fontSize: 9),
                      textAlign: TextAlign.center,
                    ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItemListPanel() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Item List', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const SizedBox(height: 12),
            if (_queueItems.isEmpty)
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 16),
                child: Text('No items added yet.'),
              )
            else
              SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: DataTable(
                  columns: const [
                    DataColumn(label: Text('Item Name')),
                    DataColumn(label: Text('Barcode')),
                    DataColumn(label: Text('MRP')),
                    DataColumn(label: Text('Selling Price')),
                    DataColumn(label: Text('Packing Date')),
                    DataColumn(label: Text('No of Labels')),
                    DataColumn(label: Text('Expiry Date')),
                    DataColumn(label: Text('')),
                  ],
                  rows: [
                    for (var i = 0; i < _queueItems.length; i++)
                      DataRow(
                        cells: [
                          DataCell(Text(_queueItems[i].product.name)),
                          DataCell(Text(_queueItems[i].product.barcode)),
                          DataCell(Text('Rs.${_queueItems[i].product.mrp.toStringAsFixed(2)}')),
                          DataCell(Text('Rs.${_queueItems[i].product.retailPrice.toStringAsFixed(2)}')),
                          DataCell(Text(
                            _queueItems[i].packingDate == null ? '—' : _formatDate(_queueItems[i].packingDate!),
                          )),
                          DataCell(Text('${_queueItems[i].copies}')),
                          DataCell(Text(_queueItems[i].expiryDate == null ? '—' : _formatDate(_queueItems[i].expiryDate!))),
                          DataCell(
                            IconButton(
                              icon: const Icon(Icons.delete, color: Colors.red),
                              tooltip: 'Remove',
                              onPressed: () => _removeQueueItem(i),
                            ),
                          ),
                        ],
                      ),
                  ],
                ),
              ),
          ],
        ),
      ),
    );
  }
}
