import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/widgets/app_scaffold.dart';
import '../../../models/product_model.dart';
import '../../../repositories/product_repository.dart';
import '../../../services/barcode_label_service.dart';

/// One entry in the "Item List" queue below the input panels — a product
/// plus how many label copies to print for it, plus the cosmetic on-screen
/// fields the user typed in for their own reference.
class _BarcodeQueueItem {
  final Product product;
  final int copies;
  final String? header;
  final String? line1;
  final String? line2;
  final String? line3;
  final String? line4;

  const _BarcodeQueueItem({
    required this.product,
    required this.copies,
    this.header,
    this.line1,
    this.line2,
    this.line3,
    this.line4,
  });
}

/// Paints a rough, cosmetic bar pattern derived from the item code, purely
/// so the Preview panel looks like a barcode label. This is NOT the barcode
/// that gets printed — the real Code128 barcode is generated by
/// [BarcodeLabelService] from the product's actual barcode value.
class _BarcodeBarsPainter extends CustomPainter {
  final String data;

  _BarcodeBarsPainter(this.data);

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()..color = Colors.black;
    final seed = data.isEmpty ? '0123456789' : data;
    const barCount = 34;
    final barSlot = size.width / barCount;
    for (var i = 0; i < barCount; i++) {
      final code = seed.codeUnitAt(i % seed.length);
      final drawBar = (code + i) % 3 != 0;
      if (drawBar) {
        canvas.drawRect(
          Rect.fromLTWH(i * barSlot, 0, barSlot * 0.6, size.height),
          paint,
        );
      }
    }
  }

  @override
  bool shouldRepaint(covariant _BarcodeBarsPainter oldDelegate) => oldDelegate.data != data;
}

class BarcodeGeneratorScreen extends ConsumerStatefulWidget {
  const BarcodeGeneratorScreen({super.key});

  @override
  ConsumerState<BarcodeGeneratorScreen> createState() => _BarcodeGeneratorScreenState();
}

class _BarcodeGeneratorScreenState extends ConsumerState<BarcodeGeneratorScreen> {
  final _itemNameController = TextEditingController();
  final _itemCodeController = TextEditingController();
  final _noOfLabelsController = TextEditingController(text: '1');
  final _headerController = TextEditingController();
  final _line1Controller = TextEditingController();
  final _line2Controller = TextEditingController();
  final _line3Controller = TextEditingController();
  final _line4Controller = TextEditingController();

  final _itemNameFocusNode = FocusNode();

  List<Product> _nameSuggestions = [];
  bool _showSuggestions = false;
  Product? _selectedProduct;

  bool _isBusy = false; // name/code lookups
  bool _isPrinting = false;

  final List<_BarcodeQueueItem> _queueItems = [];

  // Bumped on every new search so a slow, stale response can't clobber a
  // newer one's results.
  int _searchRequestId = 0;

  @override
  void initState() {
    super.initState();
    _itemNameFocusNode.addListener(() {
      if (!_itemNameFocusNode.hasFocus) {
        setState(() => _showSuggestions = false);
      }
    });
  }

  @override
  void dispose() {
    _itemNameController.dispose();
    _itemCodeController.dispose();
    _noOfLabelsController.dispose();
    _headerController.dispose();
    _line1Controller.dispose();
    _line2Controller.dispose();
    _line3Controller.dispose();
    _line4Controller.dispose();
    _itemNameFocusNode.dispose();
    super.dispose();
  }

  Future<void> _onNameChanged(String query) async {
    _selectedProduct = null;
    if (query.trim().isEmpty) {
      setState(() {
        _nameSuggestions = [];
        _showSuggestions = false;
      });
      return;
    }
    final requestId = ++_searchRequestId;
    try {
      final results = await ref.read(productRepositoryProvider).search(query.trim());
      if (!mounted || requestId != _searchRequestId) return;
      setState(() {
        _nameSuggestions = results;
        _showSuggestions = results.isNotEmpty;
      });
    } catch (_) {
      // Ignore transient lookup failures — the user can still type/scan
      // the code directly.
    }
  }

  void _pickSuggestion(Product product) {
    setState(() {
      _selectedProduct = product;
      _itemNameController.text = product.displayName?.isNotEmpty == true ? product.displayName! : product.name;
      _itemCodeController.text = product.barcode;
      _nameSuggestions = [];
      _showSuggestions = false;
    });
    _itemNameFocusNode.unfocus();
  }

  Future<void> _lookupByCode(String code) async {
    final trimmed = code.trim();
    if (trimmed.isEmpty) return;
    setState(() => _isBusy = true);
    try {
      final matches = await ref.read(productRepositoryProvider).getByBarcode(trimmed);
      if (!mounted) return;
      if (matches.isNotEmpty) {
        final product = matches.first;
        setState(() {
          _selectedProduct = product;
          _itemNameController.text = product.displayName?.isNotEmpty == true ? product.displayName! : product.name;
          _itemCodeController.text = product.barcode;
        });
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('No item found for code "$trimmed"'), backgroundColor: Colors.red),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Lookup failed: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  Future<void> _addForBarcode() async {
    if (_itemNameController.text.trim().isEmpty || _itemCodeController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Item Name and Item Code are required'), backgroundColor: Colors.red),
      );
      return;
    }
    final copies = int.tryParse(_noOfLabelsController.text.trim());
    if (copies == null || copies <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No of Labels must be a positive number'), backgroundColor: Colors.red),
      );
      return;
    }

    setState(() => _isBusy = true);
    try {
      var product = _selectedProduct;
      // If the user typed/scanned the code directly rather than picking a
      // name suggestion, resolve it against the real product record now —
      // the printed PDF needs the actual Product, not just typed text.
      if (product == null || product.barcode != _itemCodeController.text.trim()) {
        final matches = await ref.read(productRepositoryProvider).getByBarcode(_itemCodeController.text.trim());
        if (matches.isEmpty) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Item Code does not match any known item'),
                backgroundColor: Colors.red,
              ),
            );
          }
          return;
        }
        product = matches.first;
      }

      setState(() {
        _queueItems.add(
          _BarcodeQueueItem(
            product: product!,
            copies: copies,
            header: _headerController.text.trim().isEmpty ? null : _headerController.text.trim(),
            line1: _line1Controller.text.trim().isEmpty ? null : _line1Controller.text.trim(),
            line2: _line2Controller.text.trim().isEmpty ? null : _line2Controller.text.trim(),
            line3: _line3Controller.text.trim().isEmpty ? null : _line3Controller.text.trim(),
            line4: _line4Controller.text.trim().isEmpty ? null : _line4Controller.text.trim(),
          ),
        );
        _itemNameController.clear();
        _itemCodeController.clear();
        _noOfLabelsController.text = '1';
        _headerController.clear();
        _line1Controller.clear();
        _line2Controller.clear();
        _line3Controller.clear();
        _line4Controller.clear();
        _selectedProduct = null;
        _nameSuggestions = [];
        _showSuggestions = false;
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Added to barcode list'), backgroundColor: Colors.green),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  void _removeQueueItem(int index) {
    setState(() => _queueItems.removeAt(index));
  }

  Future<void> _print() async {
    if (_queueItems.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Add at least one item before printing'), backgroundColor: Colors.red),
      );
      return;
    }

    setState(() => _isPrinting = true);
    try {
      // BarcodeLabelService only bakes in name/displayName/barcode/mrp — it
      // has no concept of the cosmetic Header/Line1-4 fields, so those are
      // intentionally left out of the print job (see class docs above).
      final expanded = <Product>[];
      for (final item in _queueItems) {
        expanded.addAll(List.filled(item.copies, item.product));
      }
      final pdfBytes = await BarcodeLabelService.generateLabelSheet(expanded);
      if (!mounted) return;
      await BarcodeLabelService.printLabels(context, pdfBytes);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Labels sent to printer'), backgroundColor: Colors.green),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Print failed: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isPrinting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'Barcode Generator',
      actions: [
        IconButton(
          icon: _isPrinting
              ? const SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                )
              : const Icon(Icons.print),
          tooltip: 'Print',
          onPressed: _isPrinting ? null : _print,
        ),
      ],
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            LayoutBuilder(
              builder: (context, constraints) {
                final isNarrow = constraints.maxWidth < 800;
                final formPanel = _buildFormPanel();
                final previewPanel = _buildPreviewPanel();
                if (isNarrow) {
                  return Column(
                    children: [
                      formPanel,
                      const SizedBox(height: 16),
                      previewPanel,
                    ],
                  );
                }
                return Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(flex: 3, child: formPanel),
                    const SizedBox(width: 16),
                    Expanded(flex: 2, child: previewPanel),
                  ],
                );
              },
            ),
            const SizedBox(height: 24),
            _buildItemListPanel(),
          ],
        ),
      ),
    );
  }

  Widget _buildFormPanel() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Enter item details to add for barcode',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 16),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(flex: 3, child: _buildNameField()),
                const SizedBox(width: 12),
                Expanded(
                  flex: 2,
                  child: TextField(
                    controller: _itemCodeController,
                    decoration: const InputDecoration(
                      labelText: 'Item Code *',
                      helperText: 'Type, scan, or auto-filled from Item Name',
                    ),
                    onSubmitted: _lookupByCode,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  flex: 1,
                  child: TextField(
                    controller: _noOfLabelsController,
                    decoration: const InputDecoration(labelText: 'No of Labels *'),
                    keyboardType: TextInputType.number,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _headerController,
                    decoration: const InputDecoration(labelText: 'Header'),
                    onChanged: (_) => setState(() {}),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _line1Controller,
                    decoration: const InputDecoration(labelText: 'Line 1'),
                    onChanged: (_) => setState(() {}),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _line2Controller,
                    decoration: const InputDecoration(labelText: 'Line 2'),
                    onChanged: (_) => setState(() {}),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _line3Controller,
                    decoration: const InputDecoration(labelText: 'Line 3'),
                    onChanged: (_) => setState(() {}),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _line4Controller,
                    decoration: const InputDecoration(labelText: 'Line 4'),
                    onChanged: (_) => setState(() {}),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: SizedBox(
                    height: 48,
                    child: ElevatedButton.icon(
                      onPressed: _isBusy ? null : _addForBarcode,
                      icon: _isBusy
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Icon(Icons.add),
                      label: const Text('Add for Barcode'),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildNameField() {
    return Stack(
      children: [
        TextField(
          controller: _itemNameController,
          focusNode: _itemNameFocusNode,
          decoration: const InputDecoration(labelText: 'Item Name *'),
          onChanged: _onNameChanged,
        ),
        if (_showSuggestions)
          Positioned(
            top: 58,
            left: 0,
            right: 0,
            child: Material(
              elevation: 4,
              child: ConstrainedBox(
                constraints: const BoxConstraints(maxHeight: 220),
                child: ListView.builder(
                  shrinkWrap: true,
                  padding: EdgeInsets.zero,
                  itemCount: _nameSuggestions.length,
                  itemBuilder: (context, index) {
                    final product = _nameSuggestions[index];
                    return ListTile(
                      dense: true,
                      title: Text(product.name),
                      subtitle: Text(product.barcode),
                      onTap: () => _pickSuggestion(product),
                    );
                  },
                ),
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildPreviewPanel() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Preview', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const SizedBox(height: 16),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey.shade400),
                borderRadius: BorderRadius.circular(4),
              ),
              child: Column(
                children: [
                  Text(
                    _headerController.text.trim().isEmpty ? '(Header)' : _headerController.text.trim(),
                    style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: CustomPaint(
                      painter: _BarcodeBarsPainter(_itemCodeController.text.trim()),
                      size: Size.infinite,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    _itemCodeController.text.trim().isEmpty ? '(Item Code)' : _itemCodeController.text.trim(),
                    style: const TextStyle(fontSize: 11),
                  ),
                  const SizedBox(height: 8),
                  for (final line in [
                    _line1Controller.text.trim(),
                    _line2Controller.text.trim(),
                    _line3Controller.text.trim(),
                    _line4Controller.text.trim(),
                  ])
                    if (line.isNotEmpty)
                      Text(line, style: const TextStyle(fontSize: 10), textAlign: TextAlign.center),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItemListPanel() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Item List', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const SizedBox(height: 12),
            if (_queueItems.isEmpty)
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 16),
                child: Text('No items added yet.'),
              )
            else
              SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: DataTable(
                  columns: const [
                    DataColumn(label: Text('Item Name')),
                    DataColumn(label: Text('No of Labels')),
                    DataColumn(label: Text('Header')),
                    DataColumn(label: Text('Line 1')),
                    DataColumn(label: Text('Line 2')),
                    DataColumn(label: Text('Line 3')),
                    DataColumn(label: Text('Line 4')),
                    DataColumn(label: Text('')),
                  ],
                  rows: [
                    for (var i = 0; i < _queueItems.length; i++)
                      DataRow(
                        cells: [
                          DataCell(Text(_queueItems[i].product.name)),
                          DataCell(Text('${_queueItems[i].copies}')),
                          DataCell(Text(_queueItems[i].header ?? '')),
                          DataCell(Text(_queueItems[i].line1 ?? '')),
                          DataCell(Text(_queueItems[i].line2 ?? '')),
                          DataCell(Text(_queueItems[i].line3 ?? '')),
                          DataCell(Text(_queueItems[i].line4 ?? '')),
                          DataCell(
                            IconButton(
                              icon: const Icon(Icons.delete, color: Colors.red),
                              tooltip: 'Remove',
                              onPressed: () => _removeQueueItem(i),
                            ),
                          ),
                        ],
                      ),
                  ],
                ),
              ),
          ],
        ),
      ),
    );
  }
}
